[package]
name = "mcrt"
version = "0.1.0"
authors = ["Edward Parkinson <e.j.parkinson@soton.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "*"
rand = "0.6.0"
