void bin_photon_to_histogram(Histogram_t *hist, double costheta);
void convert_weight_to_intensity(Histogram_t *hist);
void init_histogram(Histogram_t *hist);
void increment_radiation_moment_estimators(Moments_t *moments, double z_pre, double z_post, double costheta);
void init_moments(Moments_t *moments);
int main(int argc, char *argv[]);
double gsl_rand_num(double min, double max);
void init_gsl_seed(int seed);
void random_theta_phi(double *cos_theta, double *phi);
void isotropic_scatter_photon(PhotonPacket_t *packet);
double random_tau(void);
void get_all_parameters(char *file_name, Histogram_t *hist, Moments_t *moments);
union ParameterUnion get_single_parameter(FILE *f, char *name, int type);
void print_time(void);
void isotropic_emit_photon(PhotonPacket_t *packet);
void move_photon(PhotonPacket_t *packet, double ds);
void transport_all_photons(char *file_name);
void transport_single_photon(Histogram_t *hist, Moments_t *moments);
void free_moments(Moments_t *moments);
void free_hist(Histogram_t *hist);
void ouput_intensity_to_file(Histogram_t *hist);
void output_radiation_moments_to_file(Moments_t *moments);
